name: store

services:

  account:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: store
      POSTGRES_PASSWORD: s3cret0
      POSTGRES_DB: store
    ports:
      - 5432:5432 # apenas para inspecionar o DB, apenas em desenvolvimento.
