name: store

services:

  gateway:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  account:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    hostname: account
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: store
      DATABASE_PASSWORD: s3cret0
    deploy:    
      replicas: 1

  auth:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    hostname: auth

  db:
    image: postgres:latest
    hostname: db
    environment:
      POSTGRES_USER: store
      POSTGRES_PASSWORD: s3cret0
      POSTGRES_DB: store
    ports:
      - 5432:5432 # apenas para inspecionar o DB, apenas em desenvolvimento.
